### ISSUE TITLE
Creepers Do Not Have Explosion or Sound When Igniting

### ISSUE THREAD

**Issue by Darkosto** [Lothrazar/VeinCreeper#1]
Minecraft Version: 1.20.1

NeoForge Version: 47.1.79

Mod Version: 1.0,1

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):
I've added a bunch of custom creepers, but they do not explode or have any sound effects. I'm not looking for them to explode and cause damage, but to at least have the effects work.

Log file link:

Video/images/gifs (direct upload or link): 

https://clips.twitch.tv/HungrySingleIguanaAsianGlow-sLujcpdMa8y81Hop

**Comment by Lothrazar** [comment]
thanks for the report 👍  https://legacy.curseforge.com/minecraft/mc-mods/vein-creeper/files/5204442
